name: Vercel Production Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  DISCORD_WEBHOOK_ID: ${{ secrets.DISCORD_WEBHOOK_ID }}
  DISCORD_WEBHOOK_TOKEN: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
  NODE_VERSION: '20.x'
  NPM_REGISTRY_URL: 'https://registry.npmjs.org'
  PNPM_CACHE_FOLDER: .pnpm-store

on:
  push:
    branches:
      - main

jobs:
  deploy-production:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout@v3
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 9.0.6
          run_install: false

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: ${{ env.NPM_REGISTRY_URL }}
          cache: 'pnpm'

      - name: Setup npmrc
        run: |
          echo "@dev-wiki-kr:registry=https://npm.pkg.github.com"  >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.PACKAGES_TOKEN }}" >> .npmrc

      - name: Install Vercel CLI
        run: pnpm install vercel

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: notify-discord-bot
        if: ${{ success() }}
        run: npx @dev-wiki-kr/gha-tools notify-discord-bot
        env:
          DISCORD_TITLE: 'ë°°í¬ì— ì„±ê³µí•˜ì˜€ìŠµë‹ˆë‹¤. ğŸ‰'
          DISCORD_COLOR: 0x0d6efd
          DISCORD_IMAGE: 'https://github.com/dev-wiki-kr/dev-wiki/assets/85891751/50cbc9f4-c22c-4a91-a24a-84e90f246fdc'

      - name: notify-discord-bot
        if: ${{ failure() }}
        run: npx @dev-wiki-kr/gha-tools notify-discord-bot
        env:
          DISCORD_TITLE: 'ë°°í¬ì— ì‹¤íŒ¨í•˜ì˜€ìŠµë‹ˆë‹¤. âŒ'
          DISCORD_COLOR: 0xff4545
          DISCORD_IMAGE: 'https://github.com/dev-wiki-kr/dev-wiki/assets/85891751/50cbc9f4-c22c-4a91-a24a-84e90f246fdc'
